In [16]:
import numpy as np
from numpy import loadtxt

In [34]:
train_data = np.loadtxt('train.csv', delimiter=',')
test_data = np.loadtxt('test.csv', delimiter=',')
print("Train Data:\n", train_data[:100])
print("Test Data:\n", test_data[:5])

Train Data:
 [[63.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [52.  1.  0. ...  3.  3.  1.]
 [43.  1.  2. ...  1.  2.  1.]
 [53.  1.  2. ...  3.  2.  1.]]
Test Data:
 [[ 42.    1.    3.  148.  244.    0.    0.  178.    0.    0.8   2.    2.
    2.    1. ]
 [ 59.    1.    3.  178.  270.    0.    0.  145.    0.    4.2   0.    0.
    3.    1. ]
 [ 63.    0.    1.  140.  195.    0.    1.  179.    0.    0.    2.    2.
    2.    1. ]
 [ 42.    1.    2.  120.  240.    1.    1.  194.    0.    0.8   0.    0.
    3.    1. ]
 [ 50.    1.    2.  129.  196.    0.    1.  163.    0.    0.    2.    0.
    2.    1. ]]


In [82]:
# Pisahkan fitur dan label pada data training
X_train = train_data[:, :-1]  # Semua kolom kecuali kolom terakhir (fitur)
y_train = train_data[:, -1]   # Kolom terakhir (label)

# Pisahkan fitur dan label pada data test
X_test = test_data[:, :-1]  # Semua kolom kecuali kolom terakhir (fitur)
y_test = test_data[:, -1]   # Kolom terakhir (label)

X_train=X_train.T
y_train = y_train.reshape((-1,1))
y_train=y_train.T


X_test = X_test.T
y_test = y_test.reshape((-1, 1))

# Periksa bentuk data
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)


X_train shape: (13, 100)
y_train shape: (1, 100)
X_test shape: (13, 25)
y_test shape: (25, 1)


In [83]:
# Bobot dan bias untuk input layer ke hidden layer 1 (13 fitur ke 20 neuron)
w1 = np.random.rand(13, 20)
b1 = np.zeros((1, 20))

# Bobot dan bias untuk hidden layer 1 ke hidden layer 2 (20 neuron ke 10 neuron)
w2 = np.random.rand(20, 10)
b2 = np.zeros((1, 10))

# Bobot dan bias untuk hidden layer 2 ke output layer (10 neuron ke 1 output)
w3 = np.random.rand(10, 1)
b3 = np.zeros((1, 1))


In [84]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [85]:
a0 = X_train.T
learningrate = 0.001

for i in range(2000):
    # Layer input ke hidden layer 1
    z1 = np.dot(a0, w1) + b1  # Menggunakan a0 (100, 13) * w1 (13, 20) -> z1 (100, 20)
    a1 = sigmoid(z1)  # Output layer 1 (100, 20)

    z2 = np.dot(a1, w2) + b2  # a1 (100, 20) * w2 (20, 10) -> z2 (100, 10)
    a2 = sigmoid(z2)  # Output layer 2 (100, 10)

    z3 = np.dot(a2, w3) + b3  # a2 (100, 10) * w3 (10, 1) -> z3 (100, 1)
    a3 = sigmoid(z3)  # Output layer (100, 1)

    yhat = a3
    

In [86]:
# Fungsi loss (Binary Cross-Entropy Loss)
L = -y_train * np.log(yhat) - (1 - y_train) * np.log(1 - yhat)

# Rata-rata loss
m = y_train.shape[0]  # Jumlah sampel
J = (1 / m) * np.sum(L)


In [88]:
# Backpropagation
m = y_train.shape[1]  # Jumlah sampel

# Gradien error di output layer
dz3 = a3 - y_train.T  # (1, 100)

# Gradien error di hidden layer 2
dz2 = np.dot(w3.T, dz3) * a2 * (1 - a2)  # (10, 100)

# Gradien error di hidden layer 1
dz1 = np.dot(w2.T, dz2) * a1 * (1 - a1)  # (20, 100)

# Update bobot dan bias
w3 -= learning_rate * np.dot(dz3, a2.T) / m
b3 -= learning_rate * np.sum(dz3, axis=1, keepdims=True) / m

w2 -= learning_rate * np.dot(dz2, a1.T) / m
b2 -= learning_rate * np.sum(dz2, axis=1, keepdims=True) / m

w1 -= learning_rate * np.dot(dz1, a0.T) / m
b1 -= learning_rate * np.sum(dz1, axis=1, keepdims=True) / m


ValueError: shapes (1,10) and (100,1) not aligned: 10 (dim 1) != 100 (dim 0)

In [80]:
print("w3.T shape:", w3.T.shape)
print("dz3 shape:", dz3.shape)
print("a2 shape:", a2.shape)


w3.T shape: (1, 10)
dz3 shape: (1, 100)
a2 shape: (100, 10)
